# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'rails/all'
require 'sqlite3'
require 'attr_encrypted'
require 'action_view'
require 'active_support/dependencies/autoload'
require 'rspec/autorun'
require 'rspec/core'
require 'rspec/rails'
require 'active_record'
require 'savon'

require File.expand_path('../../app/salesforce/salesforce_data', __FILE__)
require File.expand_path('../../app/models/salesforce_org', __FILE__)

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.mock_with :rspec

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

ActiveRecord::Base.establish_connection(
    :adapter => 'sqlite3',
    :database => ':memory:'
)

load "db/schema.rb"

